### ISSUE TITLE
构造插件数据失败

### ISSUE THREAD

**Issue by PackageInstaller** [sophisticate9008/draw_helper#4]
![image](https://user-images.githubusercontent.com/80018096/213109633-d34c39de-1a7e-450d-968f-d2d21e42f712.png)

**Comment by sophisticate9008** [comment]
影响使用不，我看后面代码都执行了

**Comment by PackageInstaller** [comment]
除了语音方面报错（好像是nb的原因），其他正常，感谢大佬

**Comment by PackageInstaller** [comment]
好像只有这个插件的语音无法发出，真寻自带的钉宫语音是能正常发送出去，具体报错如图，麻烦大佬帮我看看
![Screenshot_20230119_173648](https://user-images.githubusercontent.com/80018096/213407630-3d6036b8-244b-464a-b2eb-ce452e409214.png)

**Comment by PackageInstaller** [comment]
go-cqhttp给的是这个warning

[2023-01-19 17:36:45] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "https://static.prts.wiki/voice/char_388_mint/CN_034.wav?filename=\u6233\u4e00\u4e0b.wav", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exit status 1 将忽略本段CQ码.
[2023-01-19 17:36:45] [WARNING]: 群消息发送失败: 消息为空.

**Comment by sophisticate9008** [comment]
我也不行了
![%)RK8(`~{5PA(@43ARLWE_I](https://user-images.githubusercontent.com/94435821/213427329-49563f22-c886-49fb-a9a7-3d4e0fbe69cc.png)

**Comment by sophisticate9008** [comment]
![image](https://user-images.githubusercontent.com/94435821/213431655-2b363e7c-200b-4d1b-9fcf-ebe9c40c0da6.png)
1027行之后加
url_voice_cn = url_voice_cn.encode("unicode_escape").decode('unicode_escape')
url_voice_jp = url_voice_jp.encode("unicode_escape").decode('unicode_escape')
voice_text = voice_text.encode("unicode_escape").decode('unicode_escape')

**Comment by PackageInstaller** [comment]
![image](https://user-images.githubusercontent.com/80018096/213440987-f58c6372-28b8-400c-9ecb-38eb712f0bfc.png)
啊，加了还是报错（还是之前那个），指令是方舟猜语音

**Comment by sophisticate9008** [comment]
那网上搜搜怎么将unicode转成字符

**Comment by PackageInstaller** [comment]
啊，我不会啊
![image](https://user-images.githubusercontent.com/80018096/213645964-3dfe0650-bd01-4cfc-be5f-99d3a4b3cdc5.png)

**Comment by sophisticate9008** [comment]
decode("unicode_escape")换成encode("utf-8")试试

**Comment by PackageInstaller** [comment]
加了之后发送指令方舟猜语音，报错如下，机器人回复：网络问题，请稍后再试（我网络正常，挂不挂梯都是这个报错）
01-20 19:06:08 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.draw_helper) failed.
Traceback (most recent call last):
  File "/home/Neko/QQBot/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/Neko/QQBot/zhenxun_bot/extensive_plugin/draw_helper/__init__.py", line 254, in _
    list_voice.remove(list_voice[2])
UnboundLocalError: local variable 'list_voice' referenced before assignment

**Comment by PackageInstaller** [comment]
![image](https://user-images.githubusercontent.com/80018096/213681349-72cb2df6-bcb8-425c-9a54-9745d018abf6.png)

**Comment by PackageInstaller** [comment]
![image](https://user-images.githubusercontent.com/80018096/213681846-abc872eb-0245-4c09-b804-792c45044e22.png)

**Comment by sophisticate9008** [comment]
可能随机到那些预备干员了了，预备干员是没有语音的

**Comment by sophisticate9008** [comment]
其他有发出来么

**Comment by PackageInstaller** [comment]
不行
![Screenshot_20230120_195810](https://user-images.githubusercontent.com/80018096/213690003-c5815ab2-87f5-46e8-8dda-506bd04fadf8.png)

**Comment by sophisticate9008** [comment]
那自己百度一下怎么python怎么将unicode码转成字符串吧，然后测试测试吧（回家没有电脑

**Comment by sophisticate9008** [comment]
非常抱歉经过多次测试，不是上述问题，gocq会将我的中文变成unicode，现已经变为文件流发送而不是网址发送

**Comment by PackageInstaller** [comment]
好的，我去试试，祝大佬新年快乐啊
![-538226385babc13f](https://user-images.githubusercontent.com/80018096/214975741-2558e3f9-3818-4ee3-85f6-5c9bdb0ebdce.gif)

**Comment by PackageInstaller** [comment]
感谢大佬，没问题了
